changesetIgnorePatterns:
  - .github/**
  - .yarn/cache/**
  - "**/*.spec.{js,ts}"
  - packages/docs/**

compressionLevel: 0

enableGlobalCache: false

yarnPath: .yarn/releases/yarn-4.0.1.cjs

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
    - win32
  libc:
    - current
    - glibc