nodeLinker: "pnp"

changesetIgnorePatterns:
  - .github/**
  - .yarn/cache/**
  - "**/*.spec.{js,ts}"
  - "**/*.test-d.{js,ts}"
  - packages/docs/**

compressionLevel: 0

enableGlobalCache: false

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - current
    - glibc
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.10.3.cjs

packageExtensions:
  "lerna@*":
    dependencies:
      ci-info: "*"