catalogs:
  stable/react:
    react: ^19.2.4
    react-dom: ^19.2.4
    '@types/react': ^19.2.13
    '@types/react-dom': ^19.2.3
  stable/node:
    '@types/node': ^26.1.2
  stable/typescript:
    typescript: ^6.0.3
  stable/eslint:
    eslint: ^10.0.0
  stable/test:
    vitest: ^4.1.5
    '@vitest/coverage-istanbul': ^4.1.5
    jsdom: ^30.0.0
  stable/rolldown:
    rolldown: ^1.0.0
    rolldown-plugin-dts: ^0.28.0

changesetIgnorePatterns:
  - .github/**
  - .yarn/cache/**
  - "**/*.spec.{js,ts}"
  - "**/*.test-d.{js,ts}"
  - packages/docs/**

compressionLevel: 0

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  lerna@*:
    dependencies:
      ci-info: "*"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - current
    - glibc
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.14.1.cjs
