catalogs:
  stable/react:
    react: ^19.3.0
    react-dom: ^19.3.0
    '@types/react': ^19.3.0
    '@types/react-dom': ^19.3.0
  stable/node:
    '@types/node': ^24.12.0
  stable/typescript:
    typescript: ^6.0.3
  stable/eslint:
    eslint: ^10.0.0
  stable/test:
    vitest: ^5.0.0
    '@vitest/coverage-istanbul': ^5.0.0
    jsdom: ^30.0.0
  stable/rolldown:
    rolldown: ^1.0.0
    rolldown-plugin-dts: ^0.28.0
  stable/vite:
    vite: ^8.3.1

changesetIgnorePatterns:
  - .github/**
  - .yarn/cache/**
  - '**/*.spec.{js,ts}'
  - '**/*.test-d.{js,ts}'
  - packages/docs/**

compressionLevel: 0

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  lerna@*:
    dependencies:
      ci-info: '*'

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - current
    - glibc
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.14.1.cjs
